# Generated by Django 3.1.2 on 2020-10-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_remove_user_password copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('default_cost', models.FloatField()),
            ],
        ),
    ]
