# Generated by Django 3.1.2 on 2020-10-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='name',
        ),
    ]
