# Generated by Django 3.1.2 on 2020-10-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_auto_20201017_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostUser', models.CharField(max_length=100)),
                ('item_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('cost_per_unit', models.FloatField()),
                ('delivery_date', models.DateField()),
                ('order_deadline', models.DateField()),
                ('locations', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('order_id', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
