# Generated by Django 3.1.2 on 2020-10-18 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_order_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='hostUser',
            new_name='host_user',
        ),
        migrations.AddField(
            model_name='purchase',
            name='cost_per_unit',
            field=models.FloatField(default=1.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='host_user',
            field=models.CharField(default="Johm", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='item_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='locations',
            field=models.CharField(default="John", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='order_deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='tag',
            field=models.CharField(default="Hello", max_length=100),
            preserve_default=False,
        ),
    ]



    email = models.CharField(max_length=100)
    order_id = models.IntegerField()
    purchase_date = models.DateField()
    host_user = models.CharField(max_length=100)
    item_id = models.IntegerField()
    amount = models.IntegerField()
    cost_per_unit = models.FloatField()
    delivery_date = models.DateField()
    order_deadline = models.DateField()
    locations = models.CharField(max_length=100)
    tag = models.CharField(max_length=100)