# Generated by Django 3.1.2 on 2020-10-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_auto_20201018_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buy_in_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='fllme', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
