# Generated by Django 3.1.2 on 2020-10-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0009_item_reward_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='description', max_length=100),
            preserve_default=False,
        ),
    ]
